cagactgtggtgacccaggagccatcgttgtcagtgtcccctggaggaacagtcacgctcacttgtggcttgagctctggctcagtctctgctcgttactaccccagctggtaccagcagaccccaggccagcctccacgcacgctcatctacagcacaaacattcgttcctctggggtccctgctcgcttctctggctccatccttgggaacaaagctgccctcaccatcacgggggcccaggcaaatgatgagtctgattactactgtttattatatatggattatggcgctggggcttgggtgttcggcggagggaccaagctgaccgtcfrom openpyxl import Workbook
wb = Workbook()

ws = wb.active
ws['A129113'] = 'george'
